spring:
  application:
    name: VacationPayService
  profiles:
    active: dev

app:
  version: 0.1.5
  contact: https://t.me/score_msConfig021

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui

calculation:
  tax_percentage: 0.13
  count_digits_rounding: 2
  average_count_days_month: 29.3